# The routes of the project.
#
# Each route describes how an incoming URL is going
# to be processed by {{ .Assets.ServiceName }}.
# More information: {{ .Assets.Docs.Routes }}
"https://{{ "{default}" }}/":
  type: upstream
  upstream: "{{ .Name }}:http"

# A basic redirect definition
# More information: {{ .Assets.Docs.Routes }}examples/redirect/
"https://www.{{ "{default}" }}":
  type: redirect
  to: "https://{{ "{default}" }}/"
