name: CI

on: [ push ]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.20.x
          cache: true

      - name: Install dependencies
        run: go get ./cmd/platformify

      - name: Run tests
        run: make test

      - name: Run linter
        uses: golangci/golangci-lint-action@v3

  build:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.20.x
          cache: true

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v4
        with:
          distribution: goreleaser
          version: latest
          args: build --snapshot --clean
          workdir: .

      - name: Upload assets
        uses: actions/upload-artifact@v3
        with:
          name: platformify
          path: ./dist/*
          retention-days: 14
